config/routes.rb
VirtualTour::Application.routes.draw do
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match 'payments/save_user', :to=>'payments#save_user', :as=>'payments_save_user' ,:via=>[:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/renew_successfull', :to => 'payments#renew_successfull', :as => 'payments_renew_successfull', :via => [:get]
  match '/packages/upgrade', :to => 'packages#upgrade', :as => 'upgrade_packages', :via => [:get]
  match '/packages/upgrade_combo', :to => 'packages#upgrade_combo', :as => 'upgrade_combo_packages', :via => [:get]
  match '/packages/manual_packages',:to => 'packages#manual_packages',:as =>'packages_manual_packages',:via => [:get]
  get "packages/show"
  match '/tours/view_map' => 'tours#view_map'
  match '/tours/ind_map' => 'tours#ind_map'
  match '/tours/status_change' => 'tours#status_change'
  match '/tours/update' => 'tours#update'
  match '/tours/user_tours'=>'tours#user_tours'
  match '/paintings/set_name'=>'paintings#set_name'
  match '/paintings/set_main_image_true'=>'paintings#set_main_image_true'
  match '/paintings/update_priority'=>'paintings#update_priority'
  match '/paintings/check_name_of_pictures'=>'paintings#check_name_of_pictures'
  match '/tours/find_tours' => 'tours#find_tours'
  match '/paintings/count_rooms'=>'paintings#count_rooms'
  match '/tours/sold_out_tours' => 'tours#sold_out_tours'
  match '/tours/find_map_tours' => 'tours#find_map_tours'
 

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :registrations => "Registrations" }
  resources :paintings
  
  resources :tours 
  
  
  resources :drafts
  devise_scope :user do
    match "registrations/save_user" => "registrations#save_user"
  end

  resources :feedbacks, :except => [:edit, :update]

 
  root :to => 'home#index'
  ActiveAdmin.routes(self)

  match ':controller(/:action(/:id))(.:format)'
end

app/models/painting.rb
# == Schema Information
#
# Table name: paintings
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tour_id    :integer
#  user_id    :integer
#

class Painting < ActiveRecord::Base
  
  attr_accessible :image, :name, :pro,:remote_image_url,:priority, :select_image, :token
  #validates :priority, :uniqueness=>{:scope => :tour_id,:message => "priority aleardy assigned."}

  #  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  mount_uploader :image, ImageUploader
  validate :token, :presence => true
  before_create :add_priority
  def add_priority
    lock = Monitor.new
    lock.synchronize do
    temp_priority=Painting.where("token=?",token).maximum("priority")
    if temp_priority.present?
      self.priority=temp_priority+1;
    else
      self.priority=1;
    end
    end
  end


  
  belongs_to :tour
  belongs_to :user
  belongs_to :draft
  #belongs_to :paintable, :polymorphic => true
  #mount_uploader :image, ImageUploader
  #before_create :default_name
  validate :image_dimensions

  private

  def image_dimensions
    if FastImage.size("#{Rails.root}/public#{image}")[0]< 700 or FastImage.size("#{Rails.root}/public#{image}")[1]<500
        
      self.errors.add(:image, "Picture size Should Be more than 700X500")
    end
     

  end

  # def default_name
  #   self.name ||= "Living Room"
  # end









  #  before_update :reprocess_image, :if => :cropping?

  #  def cropping?
  #    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  #  end
  #  def default_name
  #    self.name ||= File.basename(image.filename, '.*').titleize if image
  #  end
  #def pro=(a)
  #sat=a["saturate"].to_i + 100
  #   #bright=(a["brightness"].to_i )*20  /100
  ##bright = a["brightness"].to_f*0.075
  #puts "ndkvhdkgdf"
  #   puts "convert #{Rails.root}/public#{self.image.url} -brightness-contrast #{a["brightness"].to_i},#{a["contrast"].to_i} -set option:modulate:colorspace hsb -modulate 100,#{sat} #{Rails.root}/public#{self.image.url}"
  # puts "ndkvhdkgdf"
  # puts "ndkvhdkgdf"
  #system <<-COMMAND
  #convert #{Rails.root}/public#{self.image.url} -brightness-contrast #{a["brightness"].to_i},#{a["contrast"].to_i} -set option:modulate:colorspace hsb -modulate 100,#{sat} #{Rails.root}/public#{self.image.url}
  #convert #{Rails.root}/public#{self.image.url(:thumb)} -brightness-contrast #{a["brightness"].to_i},#{a["contrast"].to_i} -set option:modulate:colorspace hsb -modulate 100,#{sat} #{Rails.root}/public#{self.image.url(:thumb)}
  #convert #{Rails.root}/public#{self.image.url(:small)} -brightness-contrast #{a["brightness"].to_i},#{a["contrast"].to_i} -set option:modulate:colorspace hsb -modulate 100,#{sat} #{Rails.root}/public#{self.image.url(:small)}
  #convert #{Rails.root}/public#{self.image.url(:medium)} -brightness-contrast #{a["brightness"].to_i},#{a["contrast"].to_i} -set option:modulate:colorspace hsb -modulate 100,#{sat} #{Rails.root}/public#{self.image.url(:medium)}
  #convert #{Rails.root}/public#{self.image.url(:large)} -brightness-contrast #{a["brightness"].to_i},#{a["contrast"].to_i} -set option:modulate:colorspace hsb -modulate 100,#{sat} #{Rails.root}/public#{self.image.url(:large)}
  #COMMAND
  #
  #
  #   end

  #  private
  #  def reprocess_image
  #    image.reprocess!
  #  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_filter :verify_account_validity, :only=>["new"]
  
  # before_filter :set_default_response_format


  def index
    #@painting = Painting.new
    @paintings = Painting.all
  end

  def show
    @painting = Painting.find(params[:id])
  end
  
  def new 
    #render :layout => false
    @paintings = Painting.where(:user_id=>current_user.id,:tour_id=>nil,:draft_id=>nil).order('priority ASC')

    @painting = Painting.new
    @tour = Tour.new
    @products = current_user.subscribe_product
    @token_take=Painting.last
    @token="paint_#{@token_take.id}"
    if session[:cancel_request].nil? and !params.include?:cancel_request
      Painting.destroy_all(:user_id=>current_user.id,:tour_id=>nil,:draft_id=>nil)
    elsif !session[:cancel_request].nil?
      session[:cancel_request]=nil

    end
    #    respond_to do |format|
    #    format.js {render :layout=>false}
    #  end
    # @selected_pkgs=selected_pkgs_without_tour
  end

  def create
    @previous_count=params[:count] if params.include?"count"
    if verify_no_image then
      @painting = Painting.new(params[:painting])
      @painting.user_id= current_user.id
      puts "painitng/.............!"
      if @painting.save
        respond_to do |format|
          format.html do
            session[:cancel_request]=1
            if browser.ie9?
             render :js=>"window.location.reload(true);"
            else
            redirect_to :back
            end
          end
          format.js
        end
      else

        render :js=>"alert(#{@painting.errors[:image]})"
      end
     
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:painting][:id].to_i)
    if @painting.update_attributes(params[:painting])
      #      redirect_to :back, :notice=> "Image was successfully updated."
      flash[:success] = "Image was updated!"
      redirect_to :back
    else
      render :edit
    end
  end

  def destroy
    @painting = current_user.paintings.find(params[:id])
    if @painting.destroy
      render :nothing=>true
      #redirect_to :back
      # redirect_to paintings_url, :notice=> "Image was successfully deleted."
    end
  end
  def update_priority

    target= current_user.paintings.find(params[:id])
    target_priority=target.priority
    if params.include?"tour_id"
      other= (current_user.paintings.where(:priority=>params[:value],:tour_id=>params[:tour_id])+current_user.paintings.where(:priority=>params[:value],:tour_id=>nil,:draft_id=>nil)).compact.last
    elsif params.include? "draft_id"
      other= (current_user.paintings.where(:priority=>params[:value],:draft_id=>params[:draft_id])+current_user.paintings.where(:priority=>params[:value],:tour_id=>nil,:draft_id=>nil)).compact.last

    else
      other= current_user.paintings.where(:priority=>params[:value],:tour_id=>nil, :draft_id=>nil).last
    end


    target.update_attributes(:priority=>params[:value])
    unless other.nil?
      other.update_attributes(:priority=>target_priority)
      render :text=> "#{other.id},#{target_priority}"
    else
      render :nothing=>true
    end



  end
  
  
  def set_main_image_true
    #true or false when checking main tour images
    p =Painting.find(params[:id])
    if params[:state]=="true"
      p.update_attributes(:select_image=>true)
      
    else 
      p.update_attributes(:select_image=>false)
    end
  end
  
  
  def set_name
    painting= Painting.find(params[:id])
    painting.update_attributes(:name=>params[:name])
    if params.include?"tour_id"
      bedroom=current_user.paintings.where(:tour_id=>params[:tour_id].to_i,:name=>"Bed Room").count + current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bed Room").count
      bathroom=current_user.paintings.where(:tour_id=>params[:tour_id].to_i,:name=>"Bath Room").count + current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bath Room").count
      str = "#{bedroom},#{bathroom}"
    elsif params.include?"draft_id"
      str = "#{current_user.paintings.where(:draft_id=>[params[:draft_id].to_i,nil],:tour_id=>nil,:name=>"Bed Room").count}, #{current_user.paintings.where(:draft_id=>[params[:draft_id].to_i,nil],:tour_id=>nil,:name=>"Bath Room").count}"
    else
      str = "#{current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bed Room").count}, #{current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bath Room").count}"
    end
    render :text=>str
  end
  def count_rooms
    if params.include?"tour_id"
      bedroom=current_user.paintings.where(:tour_id=>params[:tour_id].to_i,:name=>"Bed Room").count + current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bed Room").count
      bathroom=current_user.paintings.where(:tour_id=>params[:tour_id].to_i,:name=>"Bath Room").count + current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bath Room").count
      str = "#{bedroom},#{bathroom}"
    elsif params.include?"draft_id"
      str = "#{current_user.paintings.where(:draft_id=>[params[:draft_id].to_i,nil],:tour_id=>nil,:name=>"Bed Room").count}, #{current_user.paintings.where(:draft_id=>[params[:draft_id].to_i,nil],:tour_id=>nil,:name=>"Bath Room").count}"
    else
      str = "#{current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bed Room").count}, #{current_user.paintings.where(:tour_id=>nil,:draft_id=>nil,:name=>"Bath Room").count}"
    end
    render :text=>str
  end
  def check_name_of_pictures
    unless current_user.check_name_of_pictures?
      render :text=>"1"
    else
      render :text=>"0"

    end
  end
  

  private
  #  def selected_pkgs_without_tour
  #   pkgs= current_user.selected_packages.select do|spkg|
  #
  #      spkg if spkg.tour.nil?
  #
  #    end
  #    return pkgs
  #  end
  def verify_no_image
    existing_images=0
    current_nil_image=current_user.paintings.where(:tour_id=>nil)
    limit = current_user.selected_package.pictures_for_tour
    existing_images+=@previous_count.to_i unless @previous_count.nil?
    existing_images += current_nil_image.count unless current_nil_image.nil?
    if existing_images< limit
      return true
    else
      return false
    end
  end
  private
  def get_priority
    #priority=current_user.paintings.where(:tour_id=>nil,:draft_id=>nil).maximum(:priority)
    priority=$serial_no
    priority += 1 unless priority.nil?
  end

  #  def set_default_response_format
  #      #request.format = 'js'.to_sym
  #      #
  #    end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
  
end

app/views/paintings/_form.html.erb
<style>
  .dropdown-menu{
    padding: 20px;
    width: 300px;
}
</style>


<%= form_for @painting do |f| %>
  <div class="navbar" style="border-radius:100px;">
  <div class="navbar-inner" style="border-radius:100px;">
    <ul class="nav">
      <li class="dropdown" id="menu1">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Brightness
            <b class="caret"></b>
         </a>
         <div class="dropdown-menu">
           <%=range_field_tag "painting[pro][brightness]",0,:step=>1,:min=>-100,:max=>100,:onchange=>"manipulate()"%><span id="bright_val">0</span><br/>

         </div>
       </li>
<li class="dropdown" id="menu1">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
         Contrast
            <b class="caret"></b>
         </a>
         <div class="dropdown-menu">
           <%=range_field_tag "painting[pro][contrast]",0,:step=>1,:min=>-100,:max=>100,:onchange=>"manipulate()"%><span id="cont_val">0</span><br/>

         </div>
       </li>


       <li class="dropdown" id="menu1">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Sharpness
            <b class="caret"></b>
         </a>
         <div class="dropdown-menu">
           <%=range_field_tag "painting[pro][sharpness]",0,:step=>1,:min=>0,:max=>1000,:onchange=>"sharpness()"%><span id="sharp_val">0</span><br/>

         </div>
       </li>

       <li class="dropdown" id="menu1">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">
         Saturation
            <b class="caret"></b>
         </a>
         <div class="dropdown-menu">
           <%=range_field_tag "painting[pro][saturate]",0,:step=>1,:min=>-100,:max=>100,:onchange=>"manipulate()"%><span id="sat_val">0</span><br/>

         </div>
       </li>


      

    </ul>
  </div>
</div>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>
      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :name %>
    <%#= f.text_field :name %>
  </div>
  <p>
    <div style=" ">
      <center>
<%= image_tag @painting.image_url,:id=>"image-id" %></center>
</div>
  </p>
  
  
  <div class="actions" style="float:right;">
    <%= f.submit "Apply", :class=>"btn-small btn-success"%>
 
<% end %>

<%=button_tag "undo",:onclick=>"revert()",:class=>"btn-small btn-danger"%>
    </div>

app/views/paintings/_image.html.erb
<!-- Load Feather code -->
<script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>

<!-- Instantiate Feather -->
<script type='text/javascript'>
   var featherEditor = new Aviary.Feather({
       apiKey: 'RvudU_oOFka2BrKDAVGXDQ',
       apiVersion: 2,
       tools: 'brightness,saturation,sharpness,contrast',
       appendTo: '',
       onSave: function(imageID, newURL) {
           var img = document.getElementById(imageID);
           img.src = newURL;
           $('#painting_remote_image_url  ').val(newURL);
       },
       onError: function(errorObj) {
           alert(errorObj.message);
       }
   });
   function launchEditor(id, src) {
       featherEditor.launch({
           image: id,
           url: src
       });
      return false;
   }
</script>

<div id='injection_site'></div>
<%= image_tag @painting.image_url, :id=>"image1" %>
<!-- Add an edit button, passing the HTML id of the image and the public URL of the image -->
<p><input type='image' src='http://images.aviary.com/images/edit-photo.png' value='Edit photo' onclick="return launchEditor('image1', 'http://sheltered-meadow-1295.herokuapp.com/<%=@painting.image_url%>');" /></p>
        
<%= form_for @painting, :html => {:multipart => true} do |f| %>
<%=f.hidden_field "id"%>
<%=f.hidden_field "remote_image_url"%>
<%= f.submit "Done", :class=>"btn-small btn-success"%>
<%end%>

app/views/paintings/_painting.html.erb
<!-- Load Feather code -->
<script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>
<!-- Instantiate Feather -->
<script type='text/javascript'>
   var featherEditor = new Aviary.Feather({
       apiKey: 'RvudU_oOFka2BrKDAVGXDQ',
       apiVersion: 2,
       tools: 'brightness,saturation,sharpness,contrast',
       appendTo: '',
       onSave: function(imageID, newURL) {
           var img = document.getElementById(imageID);
           img.src = newURL;
           $('#painting_remote_image_url').val(newURL);
           $('#image_updated_id').val(imageID);
           $('form#updated_image_form').submit();
       },
       onError: function(errorObj) {
           alert(errorObj.message);
       }
   });
   function launchEditor(id, src) {
       featherEditor.launch({
           image: id,
           url: src
       });
      return false;
   }
 
</script>
<div id='injection_site' ></div>
<div style="margin-left: 33px;">
<div class="painting" style="height: 195px;width: 133px;" >
  <div style="height: 89px; width: 133px;">
    <%= image_tag(painting.image_url(:small), :id => painting.id)%>
  </div>
  <div class="name">
    <%#= painting.name %>
    <%# @names= ["Living Rm", "Kitchen", "Den", "Great Rm", "Dinning Rm", "Bath Rm", "Master Batch", "Half Batch", "Master Bed Rm", "Bed Rm1", "Bed Rm2", "Bed Rm3"] %>
<%@names=["Bath Room", "Bed Room", "Bonus Rm", "Den", "Dinning Room", "Foyer", "Front", "Great Room", "Kitchen", "Living Room", "Rear", "Others"]%>
<%= select_tag "Name", options_for_select(@names), :id => "select#{painting.id}", :onchange=>"check_others(#{painting.id})" ,:prompt=>"#{painting.name ||"Select Name."}",:style=>"width: 100%"%>
 <%= check_box_tag "paintings#{painting.id}", "select_image", painting.select_image , :onclick=>"main_tour_check(#{painting.id},$('#paintings#{painting.id}').prop('checked'))" %>Tour Picture
    <div id="other-name<%=painting.id%>">
  </div>
  </div>
  
  
  <div class="actions" style="font-size:14px;">
    <%= link_to "edit", '#', :onclick=>"return launchEditor('#{painting.id}', 'http://virtualiinc.com:3000#{painting.image_url(:large)}');"%> |
    <%#= link_to "remove", painting, :method => :delete, :confirm => "Are you sure1?" %> <%#=$serial_no +=1%>
  <%= link_to "remove", "#", :class=>"removed", :id=>painting.id, :onclick=>"remove_image(#{painting.id})"%>
    <%=text_field_tag :priority,painting.priority,:class=>"priority_input_#{painting.id}", :onblur=>"change_priority(#{painting.id})" %>
    <%#*<span class="badge badge-info" style="float:right; font-weight: bold"><%=$serial_no +=1%</span>%>
    <%#=$serial_no +=1%>

  </div>
  </div>
</div>

app/views/paintings/_plupload.html.erb
<% if browser.ie? %>

<!-- Load Queue widget CSS and jQuery -->
<style type="text/css">@import url(/assets/plupload/jquery.plupload.queue/css/jquery.plupload.queue.css);</style>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>

<!-- Third party script for BrowserPlus runtime (Google Gears included in Gears runtime now) -->
<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>

<!-- Load plupload and all it's runtimes and finally the jQuery queue widget -->
<script type="text/javascript" src="/assets/plupload/plupload.full.js"></script>
<script type="text/javascript" src="/assets/plupload/jquery.plupload.queue/jquery.plupload.queue.js"></script>

<script type="text/javascript">
// Convert divs to queue widgets when the DOM is ready
$(function() {
	$("#uploader").pluploadQueue({
		// General settings
		runtimes : 'gears,flash,silverlight,browserplus,html5',
		url : '/paintings',
		max_file_size : '10mb',
		//chunk_size : '1mb',
		unique_names : true,
    file_data_name : "painting[image]",
    multipart: true,
    multipart_params: {
     "authenticity_token" : '<%= form_authenticity_token %>'
    },

		// Resize images on clientside if we can
		//resize : {width : 320, height : 240, quality : 90},
    init : {
        FilesAdded: function(up, files) {
          up.start();
        }
    },

		// Specify what files to browse for
		filters : [
			{title : "Image files", extensions : "jpg,gif,png"}
			//{title : "Zip files", extensions : "zip"}
		],

		// Flash settings
		flash_swf_url : '/assets/plupload/plupload.flash.swf',

		// Silverlight settings
		silverlight_xap_url : '/assets/plupload/plupload.silverlight.xap'
	});

  var uploader = $('#uploader').pluploadQueue();
    
  uploader.bind('StateChanged', function(uploader) {
    if (uploader.files.length === (uploader.total.uploaded + uploader.total.failed)) {
      window.location.reload(true);
    }
  });


	// Client side form validation
	$('#upload_by_rahul').submit(function(e) {
        var uploader = $('#uploader').pluploadQueue();

        // Files in queue upload them first
        if (uploader.files.length > 0) {
            // When all files are uploaded submit form
            uploader.bind('StateChanged', function() {
                if (uploader.files.length === (uploader.total.uploaded + uploader.total.failed)) {
                    $('form')[0].submit();
                }
            });
                
            uploader.start();
        } else {
            alert('You must queue at least one file.');
        }

        return false;
    });
});
</script>


<form id="upload_by_rahul">
	<div id="uploader">
		<p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
	</div>
</form>

<% end %>

app/views/paintings/create.js.erb
<%if @painting.nil?%>
$("#painting_error").html("<div class='alert'>Out of Package limit</div> ");
<%else%>
<% if @painting.new_record? %>
  alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
<% else %>
  
  $("#paintings").append("<%= j render(@painting) %>");
<% end %>
<%end%>

app/views/paintings/create_not_in_use.html.erb
<%=hidden_field_tag :painting, @painting.id%>
<script type="text/javascript">
  
  $(document).ready(function(){
    alert($('#painting').val());
    $.ajax({ url: '/paintings/create_ie', type: 'get', dataType:'script',
      data: {
        id: $('#painting').val()
      }
    });
  });
</script>

app/views/paintings/edit.html.erb
<%#*<script>%>
<%#*$(function(){%>
  <%#*$('#cropbox').Jcrop({%>
    <%#*onChange: update_crop,%>
    <%#*onSelect: update_crop,%>
    <%#*setSelect: [0, 0, 50, 50],%>
    <%#*aspectRatio: 1%>
  <%#*});%>
<%#*});%>
<%#*function update_crop(coords){%>
  <%#*$("#crop_x").val(coords.x);%>
  <%#*$("#crop_y").val(coords.y);%>
  <%#*$("#crop_w").val(coords.w);%>
  <%#*$("#crop_h").val(coords.h);%>
<%#*}%>
<%#*</script>%>


<%#*<script>%>
  <%#*$(document).ready(function(){%>
    <%#*$('#painting_pro_brightness').popover("bottom");%>
  <%#*});%>
  <%#*function manipulate(){%>
<%#*$("#bright_val").text($('#painting_pro_brightness').val());%>
   <%#*$("#cont_val").text($('#painting_pro_contrast').val());%>
   <%#*$("#sharp_val").text($('#painting_pro_sharpness').val());%>
   <%#*$("#sat_val").text($('#painting_pro_saturate').val())%>
<%#*var bright= parseInt($('#painting_pro_brightness').val());%>
<%#*var cont= parseInt($('#painting_pro_contrast').val());%>
<%#*var satu= parseInt($('#painting_pro_saturate').val());%>
<%#*var sharp= parseInt($('#painting_pro_sharpness').val());%>
  <%#*Caman("#image-id", function () {%>
<%#*this.revert();%>


 <%#*this.brightness(bright);%>
 <%#*this.contrast(cont);%>
 <%#*//this.sharpen(sharp);%>
 <%#*this.saturation(satu);%>
  <%#*this.render();%>


<%#*});}%>
<%#*function sharpness(){%>
  <%#*var sharp= parseInt($('#painting_pro_sharpness').val());%>
 <%#*Caman("#image-id", function () {%>

 <%#*this.revert();%>
<%#*this.sharpen(sharp);%>
<%#*this.render();%>
<%#*});%>
<%#*}%>
<%#*function revert(){%>
   <%#*Caman("#image-id", function () {%>
   <%#*this.revert();%>


   <%#*});%>
   <%#*$('#painting_pro_brightness').val(0);%>
<%#*$('#painting_pro_contrast').val(0);%>
<%#*$('#painting_pro_saturate').val(0);%>
<%#*$('#painting_pro_sharpness').val(0);%>
 <%#*$("#bright_val").text($('#painting_pro_brightness').val());%>
  <%#*$("#cont_val").text($('#painting_pro_contrast').val());%>
  <%#*$("#sat_val").text($('#painting_pro_saturate').val());%>
  <%#*$("#sharp_val").text($('#painting_pro_sharpness').val());%>
<%#*}%>
<%#*</script>%>
<h1>Editing Image</h1>
<%= render 'image' %>

app/views/paintings/index.html.erb
<h1>Create a Tour</h1>
<%= form_for Painting.new do |f| %>
  <%= f.label :image, "Upload Images:" %>
  <%= f.file_field :image, multiple: true, name: "painting[image]" %>
<% end %>
<div style ="float: right;margin: -50px 220px 0 0">
  <%= link_to "Continue..", '#', :class => 'btn btn-small btn-primary' %>
</div>

<div id="paintings">
  <%= render @paintings %>
</div>
<div class="clear">
</div>
<br/>

<script id="template-upload" type="text/x-tmpl">
<%#*<div class="upload">%>
  <%#*{%=o.name%}%>
  <%#*<div class="progress"><div class="bar" style="width: 0%"></div></div>%>
<%#*</div>%>
</script>

app/views/paintings/new.js.erb
  $("#paintings").html("<%= j render(@paintings) %>");

app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>

<p><%= image_tag @painting.image_url %></p>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>