config/routes.rb
VirtualTour::Application.routes.draw do
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match 'payments/save_user', :to=>'payments#save_user', :as=>'payments_save_user' ,:via=>[:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/renew_successfull', :to => 'payments#renew_successfull', :as => 'payments_renew_successfull', :via => [:get]
  match '/packages/upgrade', :to => 'packages#upgrade', :as => 'upgrade_packages', :via => [:get]
  match '/packages/upgrade_combo', :to => 'packages#upgrade_combo', :as => 'upgrade_combo_packages', :via => [:get]
  match '/packages/manual_packages',:to => 'packages#manual_packages',:as =>'packages_manual_packages',:via => [:get]
  get "packages/show"
  match '/tours/view_map' => 'tours#view_map'
  match '/tours/ind_map' => 'tours#ind_map'
  match '/tours/status_change' => 'tours#status_change'
  match '/tours/update' => 'tours#update'
  match '/tours/user_tours'=>'tours#user_tours'
  match '/paintings/set_name'=>'paintings#set_name'
  match '/paintings/set_main_image_true'=>'paintings#set_main_image_true'
  match '/paintings/update_priority'=>'paintings#update_priority'
  match '/paintings/check_name_of_pictures'=>'paintings#check_name_of_pictures'
  match '/tours/find_tours' => 'tours#find_tours'
  match '/paintings/count_rooms'=>'paintings#count_rooms'
  match '/tours/sold_out_tours' => 'tours#sold_out_tours'
  match '/tours/find_map_tours' => 'tours#find_map_tours'
 

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :registrations => "Registrations" }
  resources :paintings
  
  resources :tours 
  
  
  resources :drafts
  devise_scope :user do
    match "registrations/save_user" => "registrations#save_user"
  end

  resources :feedbacks, :except => [:edit, :update]

 
  root :to => 'home#index'
  ActiveAdmin.routes(self)

  match ':controller(/:action(/:id))(.:format)'
end

app/models/feedback.rb
# == Schema Information
#
# Table name: feedbacks
#
#  id                  :integer          not null, primary key
#  satisfaction_status :string(255)
#  content             :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#

class Feedback < ActiveRecord::Base
  attr_accessible :content, :satisfaction_status
  belongs_to :user
  scope :recent, :limit => 5, :order => 'created_at DESC'
  delegate :email,:name,:to=>:user, :prefix => true
# def user_name
#   self.user.name
# end
# def user_email
# end

  def opinion
    case self.satisfaction_status
    when 'yes'
      'Satisfied'
    when 'no'
      'UnSatisfied'
    end
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedbacks = Feedback.all
  end
  def new
    #@feedback = Feedback.new
  end
  def create
    @feedback = Feedback.new(params[:feedback])
    @feedback.user_id = current_user.id
    if @feedback.save
      flash[:notice] = "Thanks for your feedback. We look forward to serve better!" 
    else
      flash[:error] = "Sorry, Your feedback has not been submitted. kindly, try again later."
    end
     redirect_to :back
  end
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_feedback_form.html.erb
<div id="example" class="modal hide fade in" style="display: none; ">
<div class="modal-header" style="margin-left: 30px;">
  <a class="close" data-dismiss="modal">X</a>
  <h3>Feedback</h3>
</div>
<div class="modal-body" style="margin-left: 30px;">
  <%= form_for :feedback,:url=>"/feedbacks/create" do |f| %>
  <%= f.label :satisfaction_status, "Are you satisfied with our service?" %>
  <%= f.radio_button(:satisfaction_status, "yes", :checked => true) %>&nbsp;Yes<br />
  <%= f.radio_button(:satisfaction_status, "no") %>&nbsp;No<br /><br />
  <%= f.label :content, "Comments" %>
  <%= f.text_area :content, :cols => 10, :rows => 10 %><br />
  <div class="modal-footer">
  <a href="#" class="btn" data-dismiss="modal">Close</a>
  <%= f.submit "Send Feedback", :class => 'btn btn-primary' %>
</div>
<% end %>
</div>

</div>

app/views/feedbacks/index.html.erb
<% $feedbacks.each do |feedback| %>
  <%= feedback.user.name %><br />
  <%= feedback.user.email %><br />
  <%= feedback.content %>
  <%= link_to "delete", feedback_path(feedback.id), :method => :delete, :confirm => "Are you sure?" %>
<% end %>

app/views/feedbacks/new.html.erb
<%= form_for $feedback do |f| %>
  <%= f.label :satisfaction_status, "Are you satisfied with our service?" %>
  <%= f.radio_button(:satisfaction_status, "yes", :checked => true) %>Yes<br />
  <%= f.radio_button(:satisfaction_status, "no") %>No<br /><br />
  <%= f.label :content, "Comments" %>
  <%= f.text_area :content, :cols => 10, :rows => 10 %><br />
  <%= f.submit "Send Feedback", :class => 'btn btn-primary' %>
<% end %>