config/routes.rb
VirtualTour::Application.routes.draw do
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match 'payments/save_user', :to=>'payments#save_user', :as=>'payments_save_user' ,:via=>[:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/renew_successfull', :to => 'payments#renew_successfull', :as => 'payments_renew_successfull', :via => [:get]
  match '/packages/upgrade', :to => 'packages#upgrade', :as => 'upgrade_packages', :via => [:get]
  match '/packages/upgrade_combo', :to => 'packages#upgrade_combo', :as => 'upgrade_combo_packages', :via => [:get]
  match '/packages/manual_packages',:to => 'packages#manual_packages',:as =>'packages_manual_packages',:via => [:get]
  get "packages/show"
  match '/tours/view_map' => 'tours#view_map'
  match '/tours/ind_map' => 'tours#ind_map'
  match '/tours/status_change' => 'tours#status_change'
  match '/tours/update' => 'tours#update'
  match '/tours/user_tours'=>'tours#user_tours'
  match '/paintings/set_name'=>'paintings#set_name'
  match '/paintings/set_main_image_true'=>'paintings#set_main_image_true'
  match '/paintings/update_priority'=>'paintings#update_priority'
  match '/paintings/check_name_of_pictures'=>'paintings#check_name_of_pictures'
  match '/tours/find_tours' => 'tours#find_tours'
  match '/paintings/count_rooms'=>'paintings#count_rooms'
  match '/tours/sold_out_tours' => 'tours#sold_out_tours'
  match '/tours/find_map_tours' => 'tours#find_map_tours'
 

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :registrations => "Registrations" }
  resources :paintings
  
  resources :tours 
  
  
  resources :drafts
  devise_scope :user do
    match "registrations/save_user" => "registrations#save_user"
  end

  resources :feedbacks, :except => [:edit, :update]

 
  root :to => 'home#index'
  ActiveAdmin.routes(self)

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model

  attr_accessible :name, :phno, :email, :password, :password_confirmation, :add1, :add2, :state, :city, :zipcode, :remember_me, :image,:product,:package,:coupon,:terms
  attr_accessor :terms
  mount_uploader :image, ImageUploader
  has_many :tours, :dependent => :destroy
  has_many :drafts, :dependent => :destroy
  has_one :product, :through => :selected_product
  has_one :selected_product,:dependent => :destroy
  has_one :package, :through => :selected_package
  has_one :selected_package,:dependent => :destroy
  has_one :card,:dependent => :destroy
  has_many :feedbacks, :dependent => :destroy
  has_many :paintings, :dependent=>:destroy
  has_one :delayed_job, :through=>:user_delay_job, :dependent=>:destroy
  has_one :user_delay_job,  :dependent=>:destroy
  before_save :set_balance
  after_create :set_auto_destroy_event
  after_create :add_coupon_transaction, :if=> Proc.new { |user| !user.assigned_coupon.nil?}
  has_many :payments, :dependent=> :destroy
  has_one :coupon, :through=>:assigned_coupon
  has_one :assigned_coupon, :dependent => :destroy
  has_many :coupons, :through=>:coupon_transactions
  has_many :coupon_transactions
  has_one :company, :dependent => :destroy
  has_many :activities
  scope :recent, :limit => 5, :order => 'created_at DESC'
  delegate :coupon_id, :to=>:assigned_coupon, :prefix=>true
  def set_balance
    self.balance ||= 0
  end
  def trace_activity
    self.activities<<Activity.create(:activity_type=>0, :charge=>Payment.last.amount)
  end
  def address
    "#{add1} #{add2}\n#{state} #{city}\n\n#{zipcode}"
  end
  def package_name
    self.selected_package.package_name
  end
  def package_price_admin
    "$ #{self.selected_package.price}"
  end
  def product_name
    self.selected_product.product.name
  end
  def product=(pro)
    unless pro.nil?
      self.selected_product=SelectedProduct.create(:product_id=>pro.to_i)
    end
  end
  #  def company=(cmp)
  #    @comp = cmp
  #    self.company= Company.create(@comp)
  #  end
  def payment_date
    Date.today + self.selected_package.remaining_days
  end
  def package=(pkg)
    assign_package(pkg)
  end
  def coupon=(c)
    self.create_assigned_coupon(:coupon_id=>c[:id],:valid_date=>c[:valid_date])
  end
  def add_coupon_transaction
    self.coupon_transactions<<CouponTransaction.create(:coupon_id=>self.assigned_coupon_coupon_id, :email=>self.email,:name=>self.name)
  end
 
  def  assign_package(pkg)
    p=Package.find(pkg[:id].to_i)
    if pkg.include?:type_of_payment and !p.special_price.nil?
      self.selected_package=SelectedPackage.create(:package_id=>p.id,:pictures_for_tour=>p.pictures_for_tour,:payment_period_type=>pkg["type_of_payment"])
    else
      self.selected_package=SelectedPackage.create(:package_id=>p.id,:pictures_for_tour=>p.pictures_for_tour,:payment_period_type=>3)
    end
  end
  def subscribe_product
    pkg=self.selected_package.package
    a=[]
    unless pkg.package_type==2
      a<< self.selected_product.product
    else
      a<< Product.where(:category_id=>pkg.product.category_id,:product_type=>1)
      a.flatten!
    end
  end
  def subscribe_product_for_upgrade
    pkg=self.selected_package.package
    a=[]
    unless pkg.package_type==2
      a<< self.selected_product.product
    else
      a<< Product.where(:category_id=>pkg.product.category_id)
      a.flatten!
    end
  end
  def price_after_discount(total)
    total-self.assigned_coupon.coupon.value.to_f
  end
  def package_price
    price = self.selected_package.price
    if any_coupon?
      price_after_discount(price)
    else
      price
    end
  end

  def total_after_all_discounts
    price=selected_package.price
    if any_coupon?
      price=price_after_discount(price)
    end
    if balance< price
      price=price-balance
    else
      price=0
    end 
  end
  def change_balance(charged)
    if selected_package.price.to_f>charged.to_f
      self.balance -= selected_package.price.to_f - charged.to_f
      self.save
    end
  end
  def packages_for_upgarde(package_type)
    #pkg=self.selected_package.package
    #price=pkg.yearly_price
    #Package.where("product_id=:product_id AND yearly_price > :price",{:product_id=>pkg.product_id,:price=>price})

    #self.selected_product.product.packages.where(:package_type=>package_type)
    price = self.package.regular_price
    product.packages.where("regular_price>:price AND package_type=:package_type",:price=>price,:package_type=>package_type) 

  end
  def packages_for_downgrade(package_type)
    price = self.package.regular_price
    product.packages.where("regular_price>10 AND regular_price<:price AND package_type=:package_type",:price=>price,:package_type=>package_type) unless price==10
  end
  def packages_for_downgrade_combo(product_id,package_type)
    product=Product.find(product_id)
    price = self.package.regular_price
    product.packages.where("regular_price>10 AND regular_price<:price AND package_type=:package_type",:price=>price,:package_type=>package_type) unless price==10

  end
  def change_product(pro)
    self.selected_product.update_attributes(:product_id=>pro.to_i)
  end
  def change_package(pkg)
    new_package=Package.find(pkg[:id].to_i)
    previous_package=self.selected_package.package
    if new_package.regular_price >=previous_package.regular_price or self.selected_package.status!=1
      package_upgrade(pkg)
      tours_inactive if  new_package.package_type.to_i==2 and  previous_package.package_type.to_i==1
    else
      destroy_delay_job
      d =Delayed::Job.enqueue Dowgrade.new(self.id,pkg,new_package.no_of_tours,previous_package.no_of_tours),:priority=>0, :run_at=>self.selected_package.remaining_days.day.from_now
      self.user_delay_job=UserDelayJob.create(:delayed_job_id=>d.id)
      #downgrade_package(pkg,@new_package.no_of_tours,@previous_package.no_of_tours)
      msg="You have successfully Dowgraded your package. Your change package will not affect until the current package validity"
      send_message("Important Alert!",msg);
    end
  end
  def package_upgrade(pkg)
    assign_package(pkg)
    self.selected_package.tours_enable
    set_auto_destroy_event
    msg="Your have Successfully upgrade your package. Kindly, Login to your acount and check for any changes you may need."
    send_message("Important Alert!",msg);
  end
  def downgrade_package(pkg,new_no_of_tours,pre_no_of_tours)
    assign_package(pkg)
    if new_no_of_tours==0 or new_no_of_tours==pre_no_of_tours
      tours_inactive
      set_auto_destroy_event
      msg="You have Dowgraded your package. All your tour are been Inactivated. Ajust your tour according to your package and then reset them to active mode."
    else
      tours_disable
      msg="You have Dowgraded your package. All your tour are been Disabled and will be deleted after 10 day from now. Immediatly, ajust your tour according to your package and then reset them to active mode."

      d =Delayed::Job.enqueue TourDestroy.new(self.id),:priority=>0, :run_at=>10.day.from_now
      self.user_delay_job.update_attributes(:delayed_job_id=>d.id)
    end

    send_message("Important Alert!",msg);
  end

  def downgrade(pkg)
    previous_package=selected_package
    new_package= Package.find(pkg[:id])
    if previous_package.remaining_days>15 and previous_package.payment_period_type==1
      refund= (package.regular_price-new_package.regular_price).round
    else
      refund=0
    end

    activities.create(:activity_type=>1, :refund=>refund)
    update_package(new_package)
    self.balance += refund
    self.save
    tours_disable
  end
  def upgrade_charge(id)
    previous_package=selected_package
    new_package= Package.find(id)
    if previous_package.remaining_days>15 and previous_package.payment_period_type==1
      (new_package.regular_price-package.regular_price).round
    elsif  previous_package.payment_period_type==3
      new_package.regular_price
    else
      0
    end
  end 
  def upgrade(pkg)
    new_package= Package.find(pkg[:id])
    update_package(new_package)
    activities.create(:activity_type=>2, :charge=>Payment.last.amount)
  end
  def update_package(pkg)
    selected_package.update_attributes(:package_id=>pkg.id,:price=>pkg.regular_price,:status=>1,:pictures_for_tour=>pkg.pictures_for_tour)

  end

  def tours_inactive
    tours=self.tours
    unless tours.empty?
      tours.each do |tour|
        tour.update_attributes(:status=>4)
      end
    end
  end
  def tours_disable
    tours=self.tours
    unless tours.empty?
      tours.each do |tour|
        tour.update_attributes(:status=>2)
      end
    end
  end
  def tours_destroy
    tours=self.tours
    unless tours.empty?
      tours.each do |tour|
        tour.destroy
      end
    end
    if self.selected_package.status==1
      set_auto_destroy_event
      msg="All your tours are removed from virtuali. Login into your Account and create new tours. "
    else
      d =Delayed::Job.enqueue UserDestroy.new(self.id),:priority=>0, :run_at=>30.day.from_now
      self.user_delay_job.update_attributes(:delayed_job_id=>d.id)
      msg="All your tours are removed from virtuali and Your account will deleted after 30 day from now. Login into your Account and Purchase any package, to keep your account live. "

    end
    send_message("Important Alert!", msg);
  end
  def enable_tour
    s_pkg=self.selected_package
    s_pkg.update_attributes(:status=>1) unless s_pkg.status == 1
    tours=self.tours.where('status!=:status',:status=>1)
    unless tours.empty?
      tours.each do |tour|
        tour.update_attributes(:status=>1)
      end
      self.user.set_auto_destroy_event
    end
  end
     

app/views/admin/users/status.html.erb
<div class="navbar">
  <div>
    <ul class="nav unstyled" style="height:100px;margin-left: 10%;margin-top:2%;width:68%">
      <li class="active tab"><%= link_to "Tours (#{@tours.count})", '#div_tours', "data-toggle" => "tab"%> </li>
      <li class="tab"><%= link_to "Users ( #{@users.count})", "#div_user", "data-toggle" => "tab"%> </li>
      <li class="tab"><%= link_to "Sales", '#div_sales', "data-toggle" => "tab" %></li>
      <li class="tab"><%= link_to "Space Usage", '#div_usage', "data-toggle" => "tab" %></li>
    </ul>
  </div></div>
  <div class="tab-content" style="margin-left: 12%; width: 65%;height:600px;padding: 20px; float: left;">
     <div class="tab-pane" id="div_usage">
       <div  style ="background-color:rgb(229, 229, 229); border-radius:10px;margin-top: 2%;padding:5% 0%;text-align: center; ">
      <h3> Space Used : <%=@app_size%> MB.</h3>
    </div>
    </div>
  <div class="tab-pane" id="div_user"><table class="index_table index">
            <tr>
              <th>Full Name</th>
              <th>Email</th>
              <th>Ph No</th>
              <th>Packages</th>
              <th>&nbsp;</th>
            </tr>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.name %> </td>
              <td><%= user.email %></td>
              <td><%= user.phno %> </td>
              <td><%=user.package_name%></td>
              <td>
                <%= link_to "edit", edit_admin_user_path(user) %>&nbsp;
                <%= link_to "view", admin_user_path(user), :method => :get %>&nbsp;
                <%= link_to "delete", admin_user_path(user), :method => :delete, :confirm => "Are you sure?" %>
              </td>
            </tr>
            <% end %>
          </table>
  </div>
  <div class="tab-pane active" id="div_tours">
    <table class="index_table index">
           <tr>
              <th>Name</th>
              <th>Category</th>
              <th><%= sortable "status"%></th>
              <th>Inactive From</th>

            </tr>
            <% @tours.each do |t| %>
            <tr>
              <td><%= t.name.gsub(/%/, '-') %></td>
              <td> <%= t.product_name %></td>
              <td style="color: green;"><%= t.tour_status %></td>
              <% if t.status != 1  %>
              <td><%= t.updated_at.strftime("%d-%b-%y, %A (%H:%M)")%> </td>
              <% else %>
              <td>-</td>
              <% end %>
            </tr>
            <% end %>
    </table><br />
    <br />
    <span class="label label-success"> &nbsp;<b>Tours Summary!</b>&nbsp; </span><br /><br />
    <p class="text-info"><em> Number of Tours <b>Active</b> : </em><%= Tour.active.count %></p>
    <p class="text-info"><em> Number of Tours <b>Inactive</b> : </em><%= Tour.inactive.count %></p>
    <p class="text-info"><em> Number of Tours <b>Sold</b> : </em><%= Tour.sold.count %></p>
  </div>
  <div class="tab-pane" id="div_sales">
    <table class="index_table index">
      <tr>
         <th>Payment Date</th>
         <th>User Name</th>
         <th>User Email</th>
         <th>Amount($)</th>
      </tr>
      <% @payments.each do |payment| %>
            <tr>
              <td><%= payment.created_at.strftime("%d-%b-%y, %A") %></td>
              <td><%= payment.user_name %> </td>
              <td><%= payment.user_email %></td>
              <td>$<%= payment.amount %> </td>
              
            </tr>
            <% end %>
            <tr>
              <td></td>
              <td></td>
            <th>Total Amount:</th>
            <td> $<%=Payment.sum(:amount)%> </td>
            </tr>
          </table>
  </div>
</div>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<style>
  .tab{
    width:25%;
    text-align:center;
  }
  .tab > a{
    font-size:20px;
    font-weight: bold;
    line-height: 4;
    box-shadow:10px 10px 5px #888888;
    color:black!important
  }
  .tab > a:hover{
    color:#888888 !important;
  }
  .tab-pane th .current {
  padding-right: 2px;
  background-repeat: no-repeat;
  background-position: right center;
}

.tab-pane th .asc {
  background-image: url(/assets/up_arrow.gif);
}

.tab-pane th .desc {
  background-image:   url(/assets/down_arrow.gif);
}
</style>