config/routes.rb
VirtualTour::Application.routes.draw do
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match 'payments/save_user', :to=>'payments#save_user', :as=>'payments_save_user' ,:via=>[:get]
  match '/payments/thank_you', :to => 'payments#thank_you', :as => 'payments_thank_you', :via => [:get]
  match '/payments/renew_successfull', :to => 'payments#renew_successfull', :as => 'payments_renew_successfull', :via => [:get]
  match '/packages/upgrade', :to => 'packages#upgrade', :as => 'upgrade_packages', :via => [:get]
  match '/packages/upgrade_combo', :to => 'packages#upgrade_combo', :as => 'upgrade_combo_packages', :via => [:get]
  match '/packages/manual_packages',:to => 'packages#manual_packages',:as =>'packages_manual_packages',:via => [:get]
  get "packages/show"
  match '/tours/view_map' => 'tours#view_map'
  match '/tours/ind_map' => 'tours#ind_map'
  match '/tours/status_change' => 'tours#status_change'
  match '/tours/update' => 'tours#update'
  match '/tours/user_tours'=>'tours#user_tours'
  match '/paintings/set_name'=>'paintings#set_name'
  match '/paintings/set_main_image_true'=>'paintings#set_main_image_true'
  match '/paintings/update_priority'=>'paintings#update_priority'
  match '/paintings/check_name_of_pictures'=>'paintings#check_name_of_pictures'
  match '/tours/find_tours' => 'tours#find_tours'
  match '/paintings/count_rooms'=>'paintings#count_rooms'
  match '/tours/sold_out_tours' => 'tours#sold_out_tours'
  match '/tours/find_map_tours' => 'tours#find_map_tours'
 

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users,:controllers => { :registrations => "Registrations" }
  resources :paintings
  
  resources :tours 
  
  
  resources :drafts
  devise_scope :user do
    match "registrations/save_user" => "registrations#save_user"
  end

  resources :feedbacks, :except => [:edit, :update]

 
  root :to => 'home#index'
  ActiveAdmin.routes(self)

  match ':controller(/:action(/:id))(.:format)'
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :paintings
  belongs_to :user
  before_create :set_name,:send_tour_to_realtor
  def send_tour_to_realtor
  	if self.order_number.blank? && self.store_realtor.present?
     Tour.create_realtor self
   end
  end
  private
  def set_name
    self.name ||= DateTime.now.to_s
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController

  def new
  end


  def edit
    @draft=Draft.find(params[:id])
    @paintings=@draft.paintings
    if @paintings.present?
      @token=@paintings.first.token
    else
      @token="draft_#{@draft.id}"
    end  
    @painting=Painting.new
    @products = current_user.subscribe_product
    @cities=[]
    state=State.find_by_name(@draft.state)
    @cities= City.find(:all,:conditions=>{:code=>state.code}) unless state.nil?
    if session[:cancel_request].nil? and !params.include?:cancel_request
      Painting.destroy_all(:user_id=>current_user.id,:tour_id=>nil,:draft_id=>nil)
    elsif !session[:cancel_request].nil?
      session[:cancel_request]=nil
    end
    @paintings += Painting.where(:user_id=>current_user.id,:tour_id=>nil,:draft_id=>nil)
    @paintings.flatten!
    @paintings=@paintings.sort_by &:priority
    @priority=get_priority
  end
  def update
    unless params.include?:tour
      tour_creation
    else
      saved_to_draft
    end
  end

  def show
  end

  def index
    @drafts=current_user.drafts.order('updated_at DESC')
  end
  private
  def tour_creation
    @tour = Tour.new(params[:draft])
    if @tour.save
      current_user.tours << @tour
      #NotificationsMailer.tour_created_message(current_user, @tour).deliver
      @paintings=current_user.paintings.where(:tour_id => nil,:draft_id =>[nil,params[:draft][:id]])
      @paintings.each do |pic|
        @tour.paintings << pic
      end
      flash[:notice] = "Tour was created successfully."
      #redirect_to :controller => 'tours', :action => 'final_tour', :id => @tour.id
      redirect_to tour_path(@tour)
    else
      error_to_flash
      redirect_to :action=>'new', :controller=>"paintings"
    end
  end
  def saved_to_draft
    @draft = Draft.find(params[:id])
    @draft.update_attributes(params[:draft])

    current_user.paintings.where(:tour_id => nil,:draft_id => nil).each do |pic|
      @draft.paintings << pic
    end

    flash[:notice] = "Sucessfully saved to draft."
    #redirect_to :controller => 'tours', :action => 'final_tour', :id => @tour.id
    redirect_to drafts_url
  end
  def get_priority
    priority=@draft.paintings.maximum(:priority)
    priority += 1 unless priority.nil?
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_draft.html.erb
<div class="listing-grid-item">
<div class="span2 draft_img" >

   <% unless draft.paintings.where(:name=>"Front").empty?%>
    <%= link_to(image_tag(draft.paintings.where(:name=>"Front").first.image_url(:extra_small)), edit_draft_path(draft))   %>
    <%else%>
    <%= link_to(image_tag('default_very_small_home.png',:style=>"width:73;height:73;"), edit_draft_path(draft))%>
    <%end%>
  </div>
<div class="span2 draft_text"><%=link_to draft.created_at.strftime("%b-%d-%Y"), edit_draft_path(draft)%></div>
</div>
<style>
  .listing-grid-item {
    float: left;
    width: 50%;
    border: medium none;
    width:135px;
  }
  .draft_text{
    width:100px;
    margin-left:42px;
    height:100px;
}
.draft_img{
  width:105px;
}
</style>

app/views/drafts/edit.html.erb
<%#= javascript_include_tag 'jquery.session.js'%>
<div class="after_sign_in">
<% if verify_tours_allowed %>
  <%#= render '/home/account_mangement'  %>

  <div class="span12" style="width:99%;margin-left:0%;">
    <p class="title-text">Create a Tour</p>
    <%= render 'shared/error_messages', :target => @draft  %>
    <%= form_for Painting.new do |f| %>
      <%$serial_no= @priority||1%>

      <div class="row-fluid">
        <div class="span5">
          <div class="fileupload btn btn-primary ">
            <%= f.label :image, "+ Add Files", :style => 'margin-top: 5px;'%>
            <input value= <%= @token %> name="painting[token]"/>
            <%= f.file_field :image, multiple: true, name: "painting[image]" %>
          </div>
          <br/>
          <span >(Note: Picture size Should Be more than 700X500. )</span></div>
        <div class="span1">
          <%=f.submit :upload, :class=>"btn btn-primary" if browser.ie8? or browser.ie7?%>
        </div>
        <div class="span5">
          <%=link_to "re-order",{:action=>  "edit", :cancel_request=>1},:remote => true, :class=>"ie-re-order-button btn btn-primary",:onclick => "reorder()"%>
<br/>
          <span>(Note:Arrange your Pictures according to priority.)</span>
        </div>
      </div>


    <% end %>

    <span id="painting_error"></span>
    <div id="paintings">
      <%= render @paintings %>

    </div>


    <br/>
  </div>
  <%= form_for @painting,:url=>'update', :html => {:multipart => true, :id=>"updated_image_form"} do |f| %>
    <%=f.hidden_field "id",:id=>"image_updated_id"%>
    <%=f.hidden_field "remote_image_url"%>

    <%#= f.submit "Done", :class=>"btn-small btn-success"%>
  <%end%>
  <div class="span12" style="width:85%;">
    <%= form_for @draft,:html =>{:class => "form-horizontal", :id=>"edit_draft"}  do |f| %>
     <%=f.hidden_field :id%>
      <h3><legend>Tour Details:</legend></h3>
      <div class="draft_field"></div>
      <div style="float:left;">
        <div class ="control-group">
          <%= f.label "Category*", :html => {:class => 'control-label'} %>
          <%= f.select :product_id, @products.collect{|p| [p.name,p.id]},{:prompt=>"Select Category"},:class=>"required" %>
        </div>
        <div class ="control-group">
          <%= f.label "Address1*", :html => {:class => 'control-label'} %>
          <i style="font-size:12px;">( Address1 Format Ex: 19 Quaker Ridge Rd )</i><br />

          <%= f.text_field :address1,:class=>"required" %>
        </div>
        <div class ="control-group">
          <%= f.label "Address2 (Optional)", :html => {:class => 'control-label'} %>
          <%= f.text_field :address2  %>
        </div>
        <div class ="control-group">
          <%= f.label "state*", :html => {:class => 'control-label'}%>
    <%#= f.text_field :state %>

          <%=f.select :state, State.all.collect {|s| [s.name,s.name]},{:prompt=>"Select State"},:onchange=>"state_city()",:class=>"required"%>
        </div>
        <div class ="control-group">
          <%= f.label "city*", :html => {:class => 'control-label'} %>
    <%#= f.text_field :city %>
          <%#=f.select :city, {},{:prompt=>"Select City"},:class=>"required"%>
<%=f.select :city, @cities.collect {|s| [s.name,s.name]},{:prompt=>"Select City"},:class=>"required"%>
        </div>
        <div class ="control-group">
          <%= f.label :zip, "Zip Code*:", :html => {:class => 'control-label'} %>
          <%= f.text_field :zip,:class=>"required"  %>
        </div>

      </div>
      <div class="span1"></div>
      <div style="float:left; ">
        <div class="control-group">
          <%= f.label "price*" %>
          <%= f.text_field :price,:class=>"required number" %>
        </div>
        <div class="control-group">
          <%= f.label "square_footage*" %>
          <%= f.text_field :square_footage,:class=>"required digits"  %>
        </div>
        <div class="control-group">
          <%= f.label :bed_rooms %>
          <%= f.text_field :bed_rooms,:class=>"required digits" %>
        </div>
        <div class="control-group">
          <%= f.label :bath_rooms %>
          <%= f.text_field :bath_rooms,:class=>"required digits" %>
        </div>
        <div class ="control-group">
          <%= f.label "subdivision", :html => {:class => 'control-label'} %>
          <%= f.text_field :subdivision  %>
        </div>
		    <div class ="control-group">
        	<%= f.label "acreage", :html => {:class => 'control-label'} %>
        	<%= f.text_field :acreage %>
        </div>
        <div class ="control-group">
          <%= f.label "MLSID", :html => {:class => 'control-label'} %>
          <%= f.text_field :mls_id %>
        </div>
        <div class ="control-group">
          <%= f.check_box :store_realtor%> Store in realtor
        </div>
      </div>

      <div style="float:left;margin-top: 0px;margin-right:26%;width: 650px;">
        <div>
          <%= f.label :description %>
          <%= f.text_area :description, :rows => 10, :style=>"width: 87%;", :class=>'wysihtml5', :onblur=>"set_session('tour_description')" %>
        </div>
      </div>
      <div style="float:left;margin-top: 10px;clear: both;">
        <div>
          <%=f.button "Save Tour", :onclick=>"saveToDraft()",:class=>"btn btn-large btn-primary saveToDraft"%>
          <%= f.submit "Create Tour",:class => 'btn btn-large btn-primary',:id=>"submit-button" %>
          <span><%= link_to "Cancel", root_url , :tyle=> 'float:right;margin-right:120px;'%></span>
        </div>
      <% end %>
    </div>
  </div>
  <script id="template-upload" type="text/x-tmpl">
  <%#*<div class="upload">%>
  <%#*{%=o.name%}%>
  <%#*<div class="progress"><div class="bar" style="width: 0%"></div></div>%>
  <%#*</div>%>
  </script>
<%else%>
  <br/><br/><br/><br/><br/><br/>
  You have already published Sufficient Tours. To create more tours upgrade your Subscription.
<%end%>
</div>
<%= javascript_include_tag "http://jzaefferer.github.com/jquery-validation/jquery.validate.js" %>
<script>
  $(document).ready(function(){
    $('.tab:eq(6)').addClass('active');
    $("#edit_draft").validate();
    $('#submit-button').click(function(e) {
      e.preventDefault();
      $.ajax({
        type: "GET",
        url:"/paintings/check_name_of_pictures"

      }).done(function(text){

        if (text==1){
          destroy_all_sessions();
          $('form#edit_draft').submit();
        }
        else{
          alert("Please Select Name for Pictures");
        }

      });
    });
    $('.saveToDraft').click(function(e){
         e.preventDefault();
         
          $('.draft_field').html($('<input type="hidden" name="tour" id="draft" />').val(1));
         $("#edit_draft").validate().cancelSubmit = true
         $.ajax({
        type: "GET",
        url:"/paintings/check_name_of_pictures"

      }).done(function(text){

        if (text==1){
          destroy_all_sessions();
          $('form#edit_draft').submit();
        }
        else{
          alert("Please Select Name for Pictures");
        }

      });
         

    });



    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

    $.ajax({
      type: "GET",
      url:"/paintings/count_rooms",
      data:{
        draft_id : $("#draft_id").val()
      }
    }).done(function(text){

      text = text.split(',');
      var bed=parseInt(text[0]);
      var bath=parseInt(text[1]);

      $("#draft_bed_rooms").val(bed);
      $("#draft_bath_rooms").val(bath);
      // if (bath > 1){
      // alert("Caution! You have choosed Bath Room more than one.")
      //}
    });
    //assign_session_to_fields();

  });
  function grt(){
    //alert("ok");
    //return false;
  }

  function set_session(id){
    var val=$('#'+id).val();
    setCookie(id,val,1);
  }
  function  assign_session_to_fields(){
    $('#tour_address1').val(getCookie('tour_address1'));
    $('#tour_address2').val(getCookie('tour_address2'));
    $('#tour_zip').val(getCookie('tour_zip'));
    $('#tour_price').val(getCookie('tour_price'));
    $('#tour_square_footage').val(getCookie('tour_square_footage'));
    $('#tour_subdivision').val(getCookie('tour_subdivision'));
    $('#tour_description').val(getCookie('tour_description'));
    $('select option[value='+getCookie('tour_product_id') +']').attr("selected",true);
    set_city();

  }
  function destroy_all_sessions(){
    deleteCookie('tour_address1');
    deleteCookie('tour_address2');
    deleteCookie('tour_zip');
    deleteCookie('tour_price');
    deleteCookie('tour_square_footage');
    deleteCookie('tour_subdivision');
    deleteCookie('tour_description');
    deleteCookie('tour_product_id');
    deleteCookie('tour_state');
    deleteCookie('tour_city');


  }
  function set_city(){
    //setCookie('draft_state',$("#draft_state").val(),1);
    $.ajax({
      type: 'GET',
      url: "/home/state_cities",
      data: {
        'state' :  $("#draft_state").val()
      }
    }).done(function(text) {
      $('#draft_city').empty().append(text);
     // $('select option[value='+getCookie('draft_city') +']').attr("selected",true);
    });
  }
  function state_city()
  {

    $.ajax({
      type: 'GET',
      url: "/home/state_cities",
      data: {
        'state' :  $("#draft_state").val()
      }
    }).done(function(text) {
      $('#draft_city').empty().append(text);

    });
  }

  function check_others(id)
  { var name= $("#select"+id).val();
    //alert(name);
    if (name == 'Others') {
      $('#other-name'+id).show();
      $('#other-name'+id).html("<input type=text id='text"+id+"'name='name' style='width:93%;' onblur='text_field_data("+id+")'>");
    } else {
      $('#other-name'+id).hide();
      set_image_name(name, id);
    }
  }
  function text_field_data(id)
  {
    var name= $("#text"+id).val();
    //alert(name);
    if (name != "") {
      set_image_name(name, id);
    }
    else{
      alert("Name cant be empty")
    }
  }
  function reorder(){
  	$("#paintings").html('')
  }
  function set_image_name(name, id)
  {
    //var name= $("#select"+id).attr('value');

    //alert(name);

    $.ajax({
      type: "GET",
      url:"/paintings/set_name",
      data:{
        id: id,
        name: name,
        draft_id: $("#draft_id").val()
      }


    }).done(function(text){
      //alert(text);
      text = text.split(',');
      var bed=parseInt(text[0]);
      var bath=parseInt(text[1]);

      $("#draft_bed_rooms").val(bed);
      $("#draft_bath_rooms").val(bath);
      if (bath > 1){
        alert("Caution! You have choosed Bath Room more than one.")
      }
    });
  }
  function change_priority(id)
  {
    var value = $('.priority_input_'+id).val();
    $.ajax({
      type:"GET",
      url:"/paintings/update_priority",
      data:{
        id: id,
        value: value,
        draft_id: $("#draft_id").val()
      }

    }).done(function(text){
      text = text.split(',');
      var id=parseInt(text[0]);
      var value=parseInt(text[1]);
      $('.priority_input_'+id).val(value);

    });
  }

  /*$('.removed').click(function(e){
  if(confirm("Are You Sure")){
   e.preventDefault();
   $(this).closest('.painting').hide();
 // alert($(this).attr("id"));
  $.ajax({
    type:'DELETE',
    dataType: "script",
    url:'/paintings/'+$(this).attr("id")

  }).done(function(){

    $('#painting_error').html("<div class='alert'>Picture Successfully Removed. </div> ")
  });
  }else
    {
      return false;
    }
});*/
  function remove_image(id){
    if(confirm("Are You Sure")){

      $.ajax({
        type:'DELETE',
        dataType: "script",
        url:'/paintings/'+$('#'+id).attr("id")

      }).done(function(){
        $('#'+id).closest('.painting').hide();
        $('#painting_error').html("<div class='alert'>Picture Successfully Removed. </div> ")
      });
    }else
    {
      return false;
    }

  }
</script>

app/views/drafts/edit.js.erb
  $("#paintings").html("<%= j render(@paintings) %>");

app/views/drafts/index.html.erb
<div class="after_sign_in">
<h2>Drafts</h2>
<div ><%=render @drafts%></div></div>
<script>
  $(document).ready(function(){
    $('.tab:eq(6)').addClass('active');
  });
</script>

app/views/drafts/show.html.erb
<h1>Drafts#show</h1>
<p>Find me in app/views/drafts/show.html.erb</p>